version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps): "
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps): "
  - package-ecosystem: 'npm'
    directory: '/pkg/web/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps): "
